export const NIGERIAN_STATES = [
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "FCT (Abuja)",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nasarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
] as const;

export type NigerianState = (typeof NIGERIAN_STATES)[number];

export const STATE_CITIES: Record<NigerianState, string[]> = {
  Abia: ["Aba", "Umuahia", "Ohafia", "Arochukwu"],
  "Adamawa": ["Yola", "Mubi", "Jimeta", "Numan"],
  "Akwa Ibom": ["Uyo", "Eket", "Ikot Ekpene", "Abak"],
  Anambra: ["Awka", "Onitsha", "Nnewi", "Nkwerre"],
  Bauchi: ["Bauchi", "Azare", "Misau", "Jama'are"],
  Bayelsa: ["Yenagoa", "Brass", "Ogbia", "Sagbama"],
  Benue: ["Makurdi", "Gboko", "Otukpo", "Vandeikya"],
  Borno: ["Maiduguri", "Biu", "Bama", "Damboa"],
  "Cross River": ["Calabar", "Ogoja", "Ikom", "Ugep"],
  Delta: ["Warri", "Sapele", "Asaba", "Ughelli"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke", "Ishieke"],
  Edo: ["Benin City", "Auchi", "Ekpoma", "Igarra"],
  Ekiti: ["Ado-Ekiti", "Ikere-Ekiti", "Oye-Ekiti", "Iworoko"],
  Enugu: ["Enugu", "Nsukka", "Oji River", "Agbani"],
  "FCT (Abuja)": ["Garki", "Wuse", "Maitama", "Jabi", "Lugbe", "Kubwa", "Gwarinpa", "Life Camp"],
  Gombe: ["Gombe", "Bajoga", "Kaltungo", "Deba"],
  Imo: ["Owerri", "Orlu", "Okigwe", "Mbaise"],
  Jigawa: ["Dutse", "Hadejia", "Kazaure", "Gumel"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan", "Saminaka"],
  Kano: ["Kano", "Rano", "Gaya", "Dambatta"],
  Katsina: ["Katsina", "Daura", "Funtua", "Malumfashi"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri", "Zuru"],
  Kogi: ["Lokoja", "Okene", "Kabba", "Idah"],
  Kwara: ["Ilorin", "Offa", "Omu-Aran", "Patigi"],
  Lagos: ["Lagos Island", "Ikeja", "Lekki", "Ikoyi", "Victoria Island", "Surulere", "Yaba", "Ajah", "Maryland", "Ikorodu", "Badagry"],
  Nasarawa: ["Lafia", "Akwanga", "Keffi", "Nasarawa"],
  Niger: ["Minna", "Bida", "Kontagora", "Suleja"],
  Ogun: ["Abeokuta", "Ijebu-Ode", "Sango Ota", "Ilaro"],
  Ondo: ["Akure", "Ondo City", "Owo", "Ikare"],
  Osun: ["Osogbo", "Ile-Ife", "Ilesa", "Ede"],
  Oyo: ["Ibadan", "Oyo", "Ogbomoso", "Iseyin"],
  Plateau: ["Jos", "Bukuru", "Shendam", "Pankshin"],
  Rivers: ["Port Harcourt", "Obio-Akpor", "Eleme", "Bonny", "Trans Amadi", "GRA Phase 2", "GRA Phase 3", "D/Line"],
  Sokoto: ["Sokoto", "Tambuwal", "Gwadabawa", "Illela"],
  Taraba: ["Jalingo", "Wukari", "Bali", "Gembu"],
  Yobe: ["Damaturu", "Potiskum", "Gujba", "Nguru"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara", "Anka"],
};

export const BUSINESS_CATEGORIES = [
  "Restaurant",
  "Hotel",
  "Bakery",
  "Tech",
  "Salon",
  "Fashion",
  "Fitness",
  "Pharmacy",
  "Supermarket",
  "Auto Repair",
  "Event Venue",
  "Entertainment",
  "Business Services",
  "Other",
] as const;

export const PROPERTY_TYPES = [
  "Shortlet",
  "Apartment",
  "House",
  "Land",
  "Villa",
  "Studio",
  "Commercial",
  "Other",
] as const;

export const EVENT_CATEGORIES = [
  "Food & Drink",
  "Technology",
  "Music & Entertainment",
  "Arts & Culture",
  "Business",
  "Sports & Recreation",
  "Fashion",
  "Education",
  "Other",
] as const;

export const PRODUCT_CATEGORIES = [
  "Electronics",
  "Fashion",
  "Home",
  "Vehicles",
  "Property",
  "Beauty",
  "Sports",
  "Other",
] as const;
